package com.posh.model;
// default package

// Generated Mar 12, 2023, 9:11:01 PM by Hibernate Tools 6.1.7.Final

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Cartitems generated by hbm2java
 */
@Entity
@Table(name = "cartitems", catalog = "posh")
public class Cartitem implements java.io.Serializable {

    private CartitemsId id;
    private Product products;
    private Cart cart;
    private Integer quantity;

    public Cartitem() {
    }

    public Cartitem(CartitemsId id, Product products, Cart cart) {
        this.id = id;
        this.products = products;
        this.cart = cart;
    }

    public Cartitem(CartitemsId id, Product products, Cart cart, Integer quantity) {
        this.id = id;
        this.products = products;
        this.cart = cart;
        this.quantity = quantity;
    }

    @EmbeddedId

    @AttributeOverrides({
            @AttributeOverride(name = "cartId", column = @Column(name = "CartID", nullable = false)),
            @AttributeOverride(name = "productId", column = @Column(name = "product_id", nullable = false)) })
    public CartitemsId getId() {
        return this.id;
    }

    public void setId(CartitemsId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id", nullable = false, insertable = false, updatable = false)
    public Product getProducts() {
        return this.products;
    }

    public void setProducts(Product products) {
        this.products = products;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CartID", nullable = false, insertable = false, updatable = false)
    public Cart getCart() {
        return this.cart;
    }

    public void setCart(Cart cart) {
        this.cart = cart;
    }

    @Column(name = "Quantity")
    public Integer getQuantity() {
        return this.quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

}
