package com.posh.model;
// default package

// Generated Mar 12, 2023, 9:11:01 PM by Hibernate Tools 6.1.7.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Cart generated by hbm2java
 */
@Entity
@Table(name = "cart", catalog = "posh")
public class Cart implements java.io.Serializable {
    private int cartId;
    private User users;
    private BigDecimal totalPrice;
    private Set<Cartitem> cartitemses = new HashSet<>(0);

    public Cart() {
    }

    public Cart(int cartId) {
        this.cartId = cartId;
    }

    public Cart(int cartId, User users, BigDecimal totalPrice, Set<Cartitem> cartitemses) {
        this.cartId = cartId;
        this.users = users;
        this.totalPrice = totalPrice;
        this.cartitemses = cartitemses;
    }

    @Id

    @Column(name = "CartID", unique = true, nullable = false)
    public int getCartId() {
        return this.cartId;
    }

    public void setCartId(int cartId) {
        this.cartId = cartId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "UserID")
    public User getUsers() {
        return this.users;
    }

    public void setUsers(User users) {
        this.users = users;
    }

    @Column(name = "TotalPrice", precision = 10, scale = 2)
    public BigDecimal getTotalPrice() {
        return this.totalPrice;
    }

    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cart")
    public Set<Cartitem> getCartitemses() {
        return this.cartitemses;
    }

    public void setCartitemses(Set<Cartitem> cartitemses) {
        this.cartitemses = cartitemses;
    }
}