package com.posh.model;
// default package

// Generated Mar 12, 2023, 9:11:01 PM by Hibernate Tools 6.1.7.Final

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.math.BigDecimal;

/**
 * Orderitems generated by hbm2java
 */
@Entity
@Table(name = "orderitems", catalog = "posh")
public class Orderitem implements java.io.Serializable {

    private OrderitemsId id;
    private Product products;
    private Order orders;
    private Integer quantity;
    private BigDecimal price;

    public Orderitem() {
    }

    public Orderitem(OrderitemsId id, Integer quantity, BigDecimal price) {
        this.id = id;
        this.quantity = quantity;
        this.price = price;
    }

    public Orderitem(OrderitemsId id, Product products, Order orders) {
        this.id = id;
        this.products = products;
        this.orders = orders;
    }

    public Orderitem(Product products, Order orders, Integer quantity, BigDecimal price) {
        this.products = products;
        this.orders = orders;
        this.quantity = quantity;
        this.price = price;
    }

    public Orderitem(OrderitemsId id, Product products, Order orders, Integer quantity, BigDecimal price) {
        this.id = id;
        this.products = products;
        this.orders = orders;
        this.quantity = quantity;
        this.price = price;
    }

    @EmbeddedId

    @AttributeOverrides({
            @AttributeOverride(name = "orderId", column = @Column(name = "OrderID", nullable = false)),
            @AttributeOverride(name = "productId", column = @Column(name = "ProductID", nullable = false)) })
    public OrderitemsId getId() {
        return this.id;
    }

    public void setId(OrderitemsId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ProductID", nullable = false, insertable = false, updatable = false)
    public Product getProducts() {
        return this.products;
    }

    public void setProducts(Product products) {
        this.products = products;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "OrderID", nullable = false, insertable = false, updatable = false)
    public Order getOrders() {
        return this.orders;
    }

    public void setOrders(Order orders) {
        this.orders = orders;
    }

    @Column(name = "Quantity")
    public Integer getQuantity() {
        return this.quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    @Column(name = "Price", precision = 10, scale = 2)
    public BigDecimal getPrice() {
        return this.price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

}
