package com.posh.model;
// default package

// Generated Mar 12, 2023, 9:11:01 PM by Hibernate Tools 6.1.7.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name = "orders", catalog = "posh")
public class Order implements java.io.Serializable {
    private int orderId;
    private User users;
    private Date orderDate;
    private BigDecimal totalPrice;
    private Set<Orderitem> orderitemses = new HashSet<>(0);

    public Order() {
    }

    public Order(int orderId) {
        this.orderId = orderId;
    }

    public Order(int orderId, User users, Date orderDate, BigDecimal totalPrice, Set<Orderitem> orderitemses) {
        this.orderId = orderId;
        this.users = users;
        this.orderDate = orderDate;
        this.totalPrice = totalPrice;
        this.orderitemses = orderitemses;
    }

    @Id

    @Column(name = "OrderID", unique = true, nullable = false)
    public int getOrderId() {
        return this.orderId;
    }

    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "UserID")
    public User getUsers() {
        return this.users;
    }

    public void setUsers(User users) {
        this.users = users;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "OrderDate", length = 19)
    public Date getOrderDate() {
        return this.orderDate;
    }

    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    @Column(name = "TotalPrice", precision = 10, scale = 2)
    public BigDecimal getTotalPrice() {
        return this.totalPrice;
    }

    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "orders")
    public Set<Orderitem> getOrderitemses() {
        return this.orderitemses;
    }

    public void setOrderitemses(Set<Orderitem> orderitemses) {
        this.orderitemses = orderitemses;
    }

}
